# Generated by Django 5.2.8 on 2025-11-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_jornada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jornada',
        ),
    ]
